name: Java App Deployment
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and Push Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no -i /dev/null ${{ secrets.SSH_USER }}@${{ secrets.EC2_HOST }} 'bash -s' << 'ENDSSH'
          git clone https://github.com/truongmanhsang/spring-boot-github-action.git
          cd spring-boot-github-action
          docker build -t spring-boot-github-action .
          docker tag spring-boot-github-action:latest truongmanhsang/spring-boot-github-action:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push truongmanhsang/spring-boot-github-action:latest
          ENDSSH

      - name: Deploy using Kubernetes
        run: |
          ssh -o StrictHostKeyChecking=no -i /dev/null ${{ secrets.SSH_USER }}@${{ secrets.EC2_HOST }} 'bash -s' << 'ENDSSH'
          # Commands to be executed on the EC2 instance after connecting via SSH
          sudo kubectl apply -f /home/ubuntu/deployment.yml # Replace with your Kubernetes manifests
          ENDSSH
