name: Java App Deployment
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --tag truongmanhsang/spring-boot-github-action:latest .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --tag truongmanhsang/spring-boot-github-action:latest --push .

      - name: Deploy using Kubernetes
        run: |
          ssh -o StrictHostKeyChecking=no -i /dev/null ${{ secrets.SSH_USER }}@${{ secrets.EC2_HOST }} 'bash -s' << 'ENDSSH'
          # Commands to be executed on the EC2 instance after connecting via SSH
          sudo kubectl delete deployment spring-boot-app >> /dev/null
          sudo kubectl apply -f https://raw.githubusercontent.com/truongmanhsang/spring-boot-github-action/develop/deployment.yml # Replace with your Kubernetes manifests
          ENDSSH
